# Generated by Django 4.1 on 2022-08-10 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('alcunha', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=40)),
                ('rg', models.CharField(max_length=30)),
                ('ufRg', models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('SP', 'São Paulo'), ('ES', 'Espírito Santo'), ('MG', 'Minas Gerais'), ('MS', 'Mato grosso do Sul'), ('MT', 'Mato Grosso')], default='MG', max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('dtNasc', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('sigla', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('E', 'Especial')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrPonto', models.CharField(max_length=100)),
                ('dtTimeColeta', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('descri', models.CharField(max_length=240)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=240)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('dtNasc', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Midea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=244)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ratBos', models.CharField(max_length=150)),
                ('fase', models.CharField(max_length=10)),
                ('contato', models.CharField(max_length=240)),
                ('sintese', models.TextField()),
                ('objetivoGeral', models.TextField()),
                ('objetivoEspecifico', models.TextField()),
                ('evidenciasDigitais', models.TextField()),
                ('valoresBens', models.TextField()),
                ('naoBuscar', models.TextField()),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('funcionarioResp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=240)),
                ('sigla', models.CharField(max_length=20)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrPonto', models.CharField(max_length=100)),
                ('descri', models.CharField(max_length=240)),
                ('endereco', models.TextField()),
                ('latLong', models.CharField(max_length=40)),
                ('complemento', models.TextField()),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.alvo')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.operacao')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMidea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('extensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.extensao')),
                ('mimeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=240)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='Recon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacaoRecon', models.TextField()),
                ('dtPrev', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dtReal', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('infoColetadasRecon', models.TextField()),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.alvo')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('mamp', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('dtNasc', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.comarca')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=240)),
                ('nrPro', models.CharField(max_length=150)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.comarca')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.funcionario')),
                ('tipoProcedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.tipoprocedimento')),
            ],
        ),
        migrations.CreateModel(
            name='PontoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacao', models.TextField()),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.operacao')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.ponto')),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.procedimento'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipoOperacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.tipooperacao'),
        ),
        migrations.CreateModel(
            name='MideaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.evidencia')),
                ('midea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.midea')),
            ],
        ),
        migrations.AddField(
            model_name='midea',
            name='tipoMidea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.tipomidea'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.orgao'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.orgao'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.operacao'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='setorAtual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.setor'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='tipoEvidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.tipoevidencia'),
        ),
        migrations.CreateModel(
            name='EquipeRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.funcionario')),
                ('recon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.recon')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('C', 'Coordenação'), ('M', 'Membro')], default='M', max_length=1)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.funcionario')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.operacao')),
            ],
        ),
    ]
