# Generated by Django 4.0.6 on 2022-08-04 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiposProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
