# Generated by Django 4.1 on 2022-08-08 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('alcunha', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=40)),
                ('rg', models.CharField(max_length=30)),
                ('ufRg', models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('SP', 'São Paulo'), ('ES', 'Espírito Santo'), ('MG', 'Minas Gerais'), ('MS', 'Mato grosso do Sul'), ('MT', 'Mato Grosso')], default='MG', max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('dtNasc', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('sigla', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('E', 'Especial')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPonto', models.CharField(max_length=100)),
                ('idServidorMembro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrPonto', models.CharField(max_length=100)),
                ('idOperacao', models.IntegerField()),
                ('descri', models.CharField(max_length=240)),
                ('orientacaoRecon', models.TextField()),
                ('endereco', models.TextField()),
                ('latLong', models.CharField(max_length=40)),
                ('complemento', models.TextField()),
                ('resp', models.CharField(max_length=10)),
                ('idAlvo', models.IntegerField()),
                ('dtPrevRec', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dtRealRec', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('infoColetadasRecon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('descri', models.CharField(max_length=240)),
                ('nrPro', models.CharField(max_length=150)),
                ('idComarca', models.CharField(max_length=150)),
                ('idPromotor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('mamp', models.CharField(max_length=20)),
                ('idComarca', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('func', models.CharField(choices=[('MMP', 'Membro MP'), ('SMP', 'Servidor MP'), ('OF', 'Oficial da Policial Militar'), ('PR', 'Praça da Policial Militar'), ('PC', 'Policial Civil'), ('SEF', 'Servidor da SEF')], default='MMP', max_length=3)),
                ('orgao', models.CharField(choices=[('MP', 'Ministério Público'), ('PM', 'Polícia Militar'), ('PC', 'Policia Civil'), ('SF', 'Secretariua da Fazenda')], default='MMP', max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=150)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('servidorMembroIdResp', models.IntegerField()),
                ('ratBos', models.CharField(max_length=150)),
                ('fase', models.CharField(max_length=10)),
                ('contato', models.CharField(max_length=240)),
                ('sintese', models.TextField()),
                ('objetivoGeral', models.TextField()),
                ('objetivoEspecifico', models.TextField()),
                ('evidenciasDigitais', models.TextField()),
                ('valoresBens', models.TextField()),
                ('naoBuscar', models.TextField()),
                ('idProc', models.IntegerField()),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.ponto')),
            ],
        ),
    ]
