# Generated by Django 4.1 on 2022-08-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCatena', '0002_alter_procedimento_promotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='funcionarioResp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.promotor'),
        ),
    ]
