# Generated by Django 4.1 on 2022-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCatena', '0004_alter_comarca_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comarca',
            name='nome',
            field=models.CharField(max_length=240, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comarca',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='comarca',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('E', 'Especial')], default='N', max_length=1, verbose_name='Tipo'),
        ),
    ]
