# Generated by Django 4.1 on 2022-08-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCatena', '0005_alter_comarca_nome_alter_comarca_sigla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='descri',
            field=models.CharField(max_length=240, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='descri',
            field=models.CharField(max_length=240, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='recon',
            name='alvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.alvo', verbose_name='Alvo'),
        ),
        migrations.AlterField(
            model_name='recon',
            name='infoColetadasRecon',
            field=models.TextField(verbose_name='Informação Coletada'),
        ),
        migrations.AlterField(
            model_name='recon',
            name='ponto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatena.ponto', verbose_name='Ponto'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='descri',
            field=models.CharField(max_length=240, verbose_name='Descrição'),
        ),
    ]
