# Generated by Django 4.1 on 2022-08-10 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCatena', '0006_alter_funcao_descri_alter_orgao_descri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recon',
            name='dtPrev',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data Prevista'),
        ),
        migrations.AlterField(
            model_name='recon',
            name='dtReal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data do Recon'),
        ),
    ]
